### ISSUE TITLE
Installation guide

### ISSUE THREAD

**Issue by maxspahn** [dbenders1/drone_toolbox_ext_control_template#1]
Hi Denis, 
Is there already an instalation guide somewhere?
Or is it the same that you sent me before?

**Comment by dbenders1** [comment]
Hi Max,

Good point. I have just finished the installation instructions in the drone_toolbox relating to this package. It is referenced in the README now. See commit [d946ede](https://github.com/dbenders1/drone_toolbox_ext_control_template/commit/d946edea627e408245b271026ee147d305e6d9df).
